# Generated by Hand

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
