# Generated by Django 5.2.9 on 2025-12-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_education_created_by_education_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., Admin, HR, Manager, Employee)', max_length=50, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Role code for programmatic access (e.g., ADMIN, HR, MANAGER, EMPLOYEE)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (higher = more permissions). Admin=100, HR=80, Manager=50, Employee=10')),
                ('can_view_all_employees', models.BooleanField(default=False, help_text='Can view all employees')),
                ('can_create_employees', models.BooleanField(default=False, help_text='Can create new employees')),
                ('can_edit_all_employees', models.BooleanField(default=False, help_text='Can edit any employee')),
                ('can_delete_employees', models.BooleanField(default=False, help_text='Can delete employees')),
                ('can_view_subordinates', models.BooleanField(default=False, help_text='Can view subordinates')),
                ('can_approve_leave', models.BooleanField(default=False, help_text='Can approve leave requests')),
                ('can_approve_timesheet', models.BooleanField(default=False, help_text='Can approve timesheets')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Employee role for access control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.role'),
        ),
    ]
