# Generated by Django 6.0 on 2025-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_address_line1_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='Slack ID for notifications', max_length=50, null=True),
        ),
    ]
