# Generated by Django 5.2.9 on 2026-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_education_created_by_alter_education_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, help_text='Cloudinary URL or public ID for employee profile photo', max_length=500, null=True),
        ),
    ]
