# Generated by Django 6.0 on 2025-12-26 05:43

import django.db.models.deletion
from django.db import migrations, models

def add_company_id_robust(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Add Column
        try:
            cursor.execute("ALTER TABLE employees_employee ADD COLUMN company_id bigint unsigned NULL")
        except Exception as e:
            if "1060" in str(e): # Duplicate column name
                print("Column company_id already exists, skipping...")
            else:
                raise e
        
        # Add Constraint
        try:
            cursor.execute("ALTER TABLE employees_employee ADD CONSTRAINT employees_employee_company_id_fk FOREIGN KEY (company_id) REFERENCES organizations_company(id)")
        except Exception as e:
            # 1061: Duplicate key name (index), 121: Duplicate key on write (constraint)
            if "1061" in str(e) or "121" in str(e) or "Duplicate" in str(e):
                print("Constraint or Index already exists, skipping...")
            else:
                raise e

        # Add Index (Manual as backup)
        try:
            cursor.execute("CREATE INDEX employees_employee_company_id_idx ON employees_employee(company_id)")
        except Exception as e:
            if "1061" in str(e) or "Duplicate" in str(e):
                print("Index already exists, skipping...")
            else:
                raise e

def remove_company_id_robust(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE employees_employee DROP FOREIGN KEY IF EXISTS employees_employee_company_id_fk")
            cursor.execute("DROP INDEX IF EXISTS employees_employee_company_id_idx ON employees_employee")
            cursor.execute("ALTER TABLE employees_employee DROP COLUMN IF EXISTS company_id")
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_slack_user_id'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_company_id_robust, remove_company_id_robust),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='employee',
                    name='company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.company'),
                ),
            ]
        ),
    ]
