# Generated by Django 5.2.9 on 2026-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_line1_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_line2_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='city_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='country_2',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code_2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='state_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
