# Generated by Django 5.2.9 on 2026-02-09 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_address_line1_2_employee_address_line2_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('pan_card', 'PAN Card'), ('address_proof', 'Address Proof'), ('photo', 'Photo'), ('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('prev_exp_letter', 'Previous Company Experience Letter'), ('prev_offer_letter', 'Previous Company Offer Letter'), ('prev_salary_slip', 'Previous Company Salary Slip'), ('prev_other_docs', 'Previous Company Other Documents'), ('qualification_cert', 'Qualification Certificate')], max_length=50)),
                ('document_url', models.CharField(help_text='Cloudinary URL or public ID', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['document_type'],
                'unique_together': {('employee', 'document_type')},
            },
        ),
    ]
