# Generated by Django 5.2.9 on 2026-01-02 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the holiday', max_length=200)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('description', models.TextField(blank=True, help_text='Description or details about the holiday')),
                ('country', models.CharField(default='India', help_text='Country where this holiday is observed', max_length=100)),
                ('region', models.CharField(blank=True, help_text='State/Province/Region (optional, for regional holidays)', max_length=100)),
                ('holiday_type', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('religious', 'Religious'), ('cultural', 'Cultural'), ('other', 'Other')], default='national', help_text='Type of holiday', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['date'], name='holidays_ho_date_ff0760_idx'), models.Index(fields=['country'], name='holidays_ho_country_941322_idx'), models.Index(fields=['holiday_type'], name='holidays_ho_holiday_b65422_idx'), models.Index(fields=['is_active'], name='holidays_ho_is_acti_f5506c_idx')],
                'unique_together': {('name', 'date', 'country')},
            },
        ),
    ]
