# Generated by Django 5.2.9 on 2026-01-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('holidays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
