# Generated by Django 5.2.9 on 2026-02-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentname', models.CharField(max_length=255)),
                ('documentlink', models.URLField(max_length=500)),
                ('doctype', models.CharField(choices=[('Policy', 'Policy'), ('Guideline', 'Guideline'), ('FAQ', 'FAQ'), ('Form', 'Form'), ('Other', 'Other')], max_length=20)),
                ('isapplied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
