# Generated by Django 5.2.9 on 2025-12-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_aadhar_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device type name (e.g., LAPTOP, MOBILE PHONE)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the device type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_d_name_84991a_idx'), models.Index(fields=['is_active'], name='inventory_d_is_acti_d339ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('need_to_sell', 'Need To Sell'), ('damaged', 'Damaged'), ('repair', 'Under Repair'), ('retired', 'Retired'), ('lost', 'Lost'), ('other', 'Other')], default='working', help_text='Current status of the device', max_length=20)),
                ('purchase_date', models.DateField(blank=True, help_text='Date when device was purchased', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price of the device', max_digits=10, null=True)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the device')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Currently assigned employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_devices', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(help_text='Type/category of the device', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicetype')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, help_text='Date when device was returned', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the assignment')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='inventory.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Device Assignment',
                'verbose_name_plural': 'Device Assignments',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['device', 'employee'], name='inventory_d_device__3fca4f_idx'), models.Index(fields=['assigned_date'], name='inventory_d_assigne_69b3cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type', 'status'], name='inventory_d_device__4a7414_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['employee'], name='inventory_d_employe_0c2ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='inventory_d_serial__ed8962_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='inventory_d_is_acti_dfb516_idx'),
        ),
    ]
