# Generated by Django 5.2.9 on 2025-12-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_slack_user_id'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand/Manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', help_text='Physical condition of the device', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model name/number of the device', max_length=200),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='condition_at_assignment',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Device condition when assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='condition_at_return',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Device condition when returned', max_length=20),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='returned_to',
            field=models.ForeignKey(blank=True, help_text='Admin who received the returned device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_returns_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='inventory_d_status_458222_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['returned_date'], name='inventory_d_returne_eb4ff9_idx'),
        ),
    ]
