# Generated by Django 5.2.9 on 2026-01-02 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('employees', '0003_alter_education_created_by_alter_education_employee_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(help_text='Type/category of the device', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Currently assigned employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='inventory.device'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='returned_to',
            field=models.ForeignKey(blank=True, help_text='Admin who received the returned device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_returns_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
