# Generated by Django 5.2.9 on 2025-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='default_warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Default warranty period in months (e.g., 12, 24, 36)', null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='icon',
            field=models.ImageField(blank=True, help_text='Visual icon for UI/dashboard', null=True, upload_to='device_types/icons/'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_assignable',
            field=models.BooleanField(default=True, help_text='Can be assigned to employee? (True for laptop, False for office printer)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='prefix',
            field=models.CharField(blank=True, help_text='Auto-generate internal serial numbers (e.g., LAP, MOB, SIM, MOU)', max_length=10),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='requires_serial_number',
            field=models.BooleanField(default=False, help_text='Must have serial number? (True for laptops, False for mouse)'),
        ),
    ]
