# Generated by Django 5.2.9 on 2026-01-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_education_created_by_alter_education_employee_and_more'),
        ('inventory', '0002_alter_device_created_by_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='The comment/note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.device')),
                ('employee', models.ForeignKey(blank=True, help_text='Employee who made the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_comments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Device Comment',
                'verbose_name_plural': 'Device Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
