# Generated by Django 5.2.9 on 2026-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_devicecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='invoice_doc',
            field=models.CharField(blank=True, help_text='Cloudinary URL or public ID for purchase invoice', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.CharField(blank=True, help_text='Cloudinary URL or public ID for device photo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_doc',
            field=models.CharField(blank=True, help_text='Cloudinary URL or public ID for warranty document', max_length=500, null=True),
        ),
    ]
