# Generated by Django 5.2.9 on 2026-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_device_invoice_doc_device_photo_device_warranty_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecomment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('all_good', 'All Good'), ('issue', 'Issue'), ('critical_issue', 'Critical Issue')], default='all_good', max_length=20, null=True),
        ),
    ]
