# Generated by Django 6.0 on 2025-12-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_make_device_fields_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='inventory_d_interna_a2fa37_idx',
            old_name='inventory_de_interna_idx',
        ),
    ]
