"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%^s(b7710kn)icqkqos)kc4oe7cv=7p3)p#1rq#f$+lpcag1z7')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required!")

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jet', 
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'auth_app.apps.AuthAppConfig',
    "corsheaders",
    'anymail',
    'departments.apps.DepartmentsConfig',
    'employees.apps.EmployeesConfig',
    'holidays.apps.HolidaysConfig',
    'inventory.apps.InventoryConfig',
    'leaves.apps.LeavesConfig',
    'attendance.apps.AttendanceConfig',
    'payroll.apps.PayrollConfig',
    'notifications.apps.NotificationsConfig',
    'organizations.apps.OrganizationsConfig',
    'drf_yasg',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# MIDDLEWARE configuration
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be first
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": (
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Add django-filter if installed
try:
    import django_filters
    REST_FRAMEWORK["DEFAULT_FILTER_BACKENDS"] = (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    )
except ImportError:
    pass


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------- CORS & CSRF Settings for testing --------------------

from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True  # Allow all for testing
CORS_ALLOW_CREDENTIALS = False  # JWT only

# Allow all headers sent by frontend
CORS_ALLOW_HEADERS = list(default_headers) + [
    "Authorization",
    "Accept",
    "Content-Type",
    "Referer",
    "Sec-CH-UA",
    "Sec-CH-UA-Mobile",
    "Sec-CH-UA-Platform",
    "User-Agent",
]

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_URLS_REGEX = r'^/.*$'

# Allow all Vercel frontends and Render domains
CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    "https://hrms-frontend-wheat.vercel.app",
    "https://hrms-backend-4vbf.onrender.com",
    "https://hrms-backend-09fn.onrender.com",
    "https://*.onrender.com",
    "http://localhost",
    "http://127.0.0.1",
]

# Cookie security for cross-site
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_HTTPONLY = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

APPEND_SLASH = True


# -------------------- End CORS/CSRF --------------------



WSGI_APPLICATION = 'config.wsgi.application'

# Update ALLOWED_HOSTS based on environment
env_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if env_allowed_hosts:
    if env_allowed_hosts == '*':
        ALLOWED_HOSTS = ['*']
    else:
        ALLOWED_HOSTS = [h.strip() for h in env_allowed_hosts.split(',')]
elif not DEBUG:
    render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if render_hostname:
        ALLOWED_HOSTS = [render_hostname, 'localhost', '127.0.0.1']
    else:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = ['*']


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "3306"),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# SSL fixes for Render / TiDB
if 'OPTIONS' in DATABASES['default'] and 'ssl-mode' in DATABASES['default']['OPTIONS']:
    del DATABASES['default']['OPTIONS']['ssl-mode']

db_host = DATABASES['default'].get('HOST', '')
if os.environ.get('RENDER') or (db_host and 'tidbcloud.com' in db_host):
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    if 'ssl-mode' in DATABASES['default']['OPTIONS']:
        del DATABASES['default']['OPTIONS']['ssl-mode']

    import sys
    is_pymysql = 'pymysql' in sys.modules
    if is_pymysql:
        DATABASES['default']['OPTIONS']['ssl'] = {'ssl_mode': 'REQUIRED'}
    else:
        DATABASES['default']['OPTIONS']['ssl_mode'] = 'REQUIRED'
        DATABASES['default']['OPTIONS']['ssl'] = {}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "auth_app.User"

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Kolkata')
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

# Email
ANYMAIL = {
   "SENDINBLUE_API_KEY": os.getenv("MAILGUN_API_KEY"),
}
EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
DEFAULT_FROM_EMAIL = "HRMS <devpython549@gmail.com>"

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "Type in the *'Value'* input box below: **Bearer &lt;your_token&gt;**<br>Example: `Bearer eyJhbGci...`"
        }
    },
    'USE_SESSION_AUTH': False,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler',},},
    'root': {'handlers': ['console'], 'level': 'DEBUG',},
}

# Attendance Settings
ATTENDANCE_DEFAULT_WORKING_HOURS = os.environ.get('ATTENDANCE_DEFAULT_WORKING_HOURS', '09:00')
ATTENDANCE_DEFAULT_TOTAL_TIME_SECONDS = int(os.environ.get('ATTENDANCE_DEFAULT_TOTAL_TIME_SECONDS', '32400'))  # 9 hours
ATTENDANCE_HALF_DAY_THRESHOLD = float(os.environ.get('ATTENDANCE_HALF_DAY_THRESHOLD', '0.5'))  # 50% of scheduled time
