# Generated by Django 5.2.9 on 2026-01-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(help_text='Name of the restricted holiday', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this RH is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('day_status', models.CharField(blank=True, help_text='e.g. First Half, Second Half', max_length=50, null=True)),
                ('late_reason', models.TextField(blank=True, null=True)),
                ('doc_link', models.CharField(blank=True, help_text='Path to document (e.g. hrms/uploads/abc123.jpg)', max_length=500, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rh_dates', models.JSONField(blank=True, default=list, help_text='List of Restricted Holiday dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_constraint=False, help_text='Employee applying for leave', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Other', 'Other')], max_length=50)),
                ('year', models.IntegerField(help_text='Fiscal year (e.g., 2025)')),
                ('total_allocated', models.DecimalField(decimal_places=1, default=0, help_text='Total allocated (quota + carry forward)', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, help_text='Leaves carried forward from previous year', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0, help_text='Approved leaves taken', max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0, help_text='Leaves pending approval', max_digits=5)),
                ('rh_allocated', models.IntegerField(default=0, help_text='RH days allocated')),
                ('rh_used', models.IntegerField(default=0, help_text='RH days used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_constraint=False, help_text='Employee whose balance is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Other', 'Other')], max_length=50)),
                ('monthly_quota', models.DecimalField(decimal_places=1, default=0, help_text='Leaves allocated per month', max_digits=5)),
                ('yearly_quota', models.DecimalField(decimal_places=1, default=0, help_text='Total leaves allocated per year', max_digits=5)),
                ('rh_quota', models.IntegerField(default=2, help_text='Number of Restricted Holidays allowed per year')),
                ('carry_forward_limit', models.DecimalField(decimal_places=1, default=0, help_text='Maximum leaves that can be carried forward to next year', max_digits=5)),
                ('effective_from', models.DateField(help_text='Quota effective from this date')),
                ('effective_to', models.DateField(blank=True, help_text='Quota valid until this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_constraint=False, help_text='Employee for whom quota is configured', on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('employee', 'leave_type', 'effective_from')},
            },
        ),
    ]
