# Generated by Django 6.0 on 2025-12-21 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('day_status', models.CharField(blank=True, help_text='e.g. First Half, Second Half', max_length=50, null=True)),
                ('late_reason', models.TextField(blank=True, null=True)),
                ('doc_link', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rh_dates', models.JSONField(blank=True, default=list, help_text='List of Restricted Holiday dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
