# Generated by Django 5.2.9 on 2026-01-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('employees', '0003_alter_education_created_by_alter_education_employee_and_more'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(help_text='Employee applying for leave', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose balance is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='employee',
            field=models.ForeignKey(help_text='Employee for whom quota is configured', on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='employees.employee'),
        ),
    ]
