# Generated by Django 6.0 on 2025-12-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='doc_link',
            field=models.CharField(blank=True, help_text='Path to document (e.g. hrms/uploads/abc123.jpg)', max_length=500, null=True),
        ),
    ]
