# Generated by Django 5.2.9 on 2026-01-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leave_employee_alter_leavebalance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='restricted_holiday',
            field=models.ForeignKey(blank=True, help_text='Selected Restricted Holiday (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications', to='leaves.restrictedholiday'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Restricted Holiday', 'Restricted Holiday'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Restricted Holiday', 'Restricted Holiday'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Restricted Holiday', 'Restricted Holiday'), ('Other', 'Other')], max_length=50),
        ),
    ]
