# Generated by Django 6.0 on 2025-12-22 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_aadhar_number_and_more'),
        ('leaves', '0002_restrictedholiday_leavebalance_leavequota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(help_text='Employee applying for leave', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose balance is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='employee',
            field=models.ForeignKey(help_text='Employee for whom quota is configured', on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='employees.employee'),
        ),
    ]
