# Generated by Django 5.2.9 on 2026-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_restricted_holiday_alter_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='rh_pending',
            field=models.IntegerField(default=0, help_text='RH days pending approval'),
        ),
    ]
