# Generated by Django 5.2.9 on 2026-01-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_education_created_by_alter_education_employee_and_more'),
        ('payroll', '0002_alter_payslip_employee_alter_payslip_generated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='allocated_leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='final_leave_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='misc_deduction_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='applicable_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='applicable_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='increment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='leaves_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.employee'),
        ),
    ]
