# Generated by Django 5.2.9 on 2026-01-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_33d25b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_35a421_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department', 'level'], name='departments_departm_aea34c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('name', 'department')},
        ),
    ]
