# Generated by Django 6.0 on 2025-12-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Step 1: Add the column as a simple bigint (Signed, based on previous incompatibility error)
                migrations.RunSQL(
                    sql="ALTER TABLE departments_department ADD COLUMN manager_id bigint NULL",
                    reverse_sql="ALTER TABLE departments_department DROP COLUMN manager_id"
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='department',
                    name='manager',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
                ),
            ]
        ),
        # Step 2: Add the Foreign Key constraint in a separate command to avoid TiDB race conditions
        migrations.RunSQL(
            sql="ALTER TABLE departments_department ADD CONSTRAINT departments_department_manager_id_fk FOREIGN KEY (manager_id) REFERENCES employees_employee(id)",
            reverse_sql="ALTER TABLE departments_department DROP FOREIGN KEY departments_department_manager_id_fk"
        ),
    ]
