# Generated by Django 5.2.9 on 2026-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('office_in_time', models.DateTimeField(blank=True, null=True)),
                ('office_out_time', models.DateTimeField(blank=True, null=True)),
                ('home_in_time', models.DateTimeField(blank=True, null=True)),
                ('home_out_time', models.DateTimeField(blank=True, null=True)),
                ('office_working_hours', models.CharField(default='09:00', max_length=10)),
                ('orignal_total_time', models.IntegerField(default=32400)),
                ('seconds_actual_worked_time', models.IntegerField(default=0)),
                ('seconds_actual_working_time', models.IntegerField(default=0)),
                ('seconds_extra_time', models.IntegerField(default=0)),
                ('office_time_inside', models.IntegerField(default=0)),
                ('office_seconds_worked', models.IntegerField(default=0)),
                ('home_seconds_worked', models.IntegerField(default=0)),
                ('day_type', models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='WORKING_DAY', max_length=20)),
                ('extra_time_status', models.CharField(blank=True, choices=[('+', 'Overtime'), ('-', 'Undertime'), ('', 'No Extra Time')], default='', max_length=1)),
                ('admin_alert', models.IntegerField(default=0)),
                ('admin_alert_message', models.CharField(blank=True, max_length=200)),
                ('day_text', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('standup_time', models.DateTimeField(blank=True, null=True)),
                ('report_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_start_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_day_before_joining', models.BooleanField(default=False)),
                ('is_working_from_home', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ManualAttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('hours', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
