# Generated by Django 6.0 on 2025-12-26 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('hours', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_requests', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Attendance date')),
                ('in_time', models.DateTimeField(blank=True, help_text='Check-in time (calculated from location times)', null=True)),
                ('out_time', models.DateTimeField(blank=True, help_text='Check-out time (calculated from location times)', null=True)),
                ('office_in_time', models.DateTimeField(blank=True, help_text='Office check-in time', null=True)),
                ('office_out_time', models.DateTimeField(blank=True, help_text='Office check-out time', null=True)),
                ('home_in_time', models.DateTimeField(blank=True, help_text='Home check-in time', null=True)),
                ('home_out_time', models.DateTimeField(blank=True, help_text='Home check-out time', null=True)),
                ('office_working_hours', models.CharField(default='09:00', help_text="Scheduled working hours (e.g., '09:00', '10:38')", max_length=10)),
                ('orignal_total_time', models.IntegerField(default=32400, help_text='Scheduled total time in seconds (default from settings)')),
                ('seconds_actual_worked_time', models.IntegerField(default=0, help_text='Actual time worked in seconds')),
                ('seconds_actual_working_time', models.IntegerField(default=0, help_text='Actual working time in seconds')),
                ('seconds_extra_time', models.IntegerField(default=0, help_text='Extra/overtime in seconds (can be negative for undertime)')),
                ('office_time_inside', models.IntegerField(default=0, help_text='Time spent inside office in seconds')),
                ('office_seconds_worked', models.IntegerField(default=0, help_text='Time worked at office in seconds')),
                ('home_seconds_worked', models.IntegerField(default=0, help_text='Time worked at home in seconds')),
                ('day_type', models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='WORKING_DAY', help_text='Type of day', max_length=20)),
                ('extra_time_status', models.CharField(blank=True, choices=[('+', 'Overtime'), ('-', 'Undertime'), ('', 'No Extra Time')], default='', help_text='Status of extra time (+ for overtime, - for undertime)', max_length=1)),
                ('admin_alert', models.IntegerField(default=0, help_text='Admin alert flag (0 or 1)')),
                ('admin_alert_message', models.CharField(blank=True, help_text="Admin alert message (e.g., 'In/Out Time Missing')", max_length=200)),
                ('day_text', models.TextField(blank=True, help_text="Day text message (e.g., 'Previous month pending time merged!!')")),
                ('text', models.TextField(blank=True, help_text='Additional text field')),
                ('standup_time', models.DateTimeField(blank=True, null=True)),
                ('report_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_start_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_day_before_joining', models.BooleanField(default=False, help_text='Is this day before employee joining date')),
                ('is_working_from_home', models.BooleanField(default=False, help_text='Is employee working from home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', 'employee'],
                'indexes': [
                    models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
                    models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
                    models.Index(fields=['day_type'], name='attendance__day_typ_d78ccf_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_attendance'),
                ],
            },
        ),
    ]
