# Generated by Django 5.2.9 on 2025-12-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0002_education_created_by_education_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='admin_alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='admin_alert_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='WORKING_DAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='extra_time_status',
            field=models.CharField(blank=True, choices=[('+', 'Overtime'), ('-', 'Undertime'), ('', 'No Extra Time')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='home_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='home_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='home_seconds_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_day_before_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_working_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='office_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='office_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='office_seconds_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='office_time_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='office_working_hours',
            field=models.CharField(default='09:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='orignal_total_time',
            field=models.IntegerField(default=32400),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='seconds_actual_worked_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='seconds_actual_working_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='seconds_extra_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
