# Generated by Django 5.2.9 on 2025-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_day_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='home_in_time',
            field=models.DateTimeField(blank=True, help_text='Home check-in time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='home_out_time',
            field=models.DateTimeField(blank=True, help_text='Home check-out time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='home_seconds_worked',
            field=models.IntegerField(default=0, help_text='Time worked at home in seconds'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='office_in_time',
            field=models.DateTimeField(blank=True, help_text='Office check-in time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='office_out_time',
            field=models.DateTimeField(blank=True, help_text='Office check-out time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='office_seconds_worked',
            field=models.IntegerField(default=0, help_text='Time worked at office in seconds'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.DateTimeField(blank=True, help_text='Check-in time (calculated from location times)', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.DateTimeField(blank=True, help_text='Check-out time (calculated from location times)', null=True),
        ),
    ]
