# Generated by Django 5.2.9 on 2026-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_timesheet_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tracker_screenshot',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
