# Generated by Django 5.2.9 on 2025-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_home_in_time_attendance_home_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_working_from_home',
            field=models.BooleanField(default=False, help_text='Is employee working from home'),
        ),
    ]

