# Generated by Django 5.2.9 on 2025-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_is_working_from_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(
                choices=[
                    ('WORKING_DAY', 'Working Day'),
                    ('HALF_DAY', 'Half Day'),
                    ('LEAVE_DAY', 'Leave Day'),
                    ('HOLIDAY', 'Holiday'),
                    ('WEEKEND_OFF', 'Weekend Off'),
                ],
                default='WORKING_DAY',
                help_text='Type of day',
                max_length=20
            ),
        ),
    ]

