# Generated by Django 5.2.9 on 2026-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_tracker_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off'), ('ABSENT', 'Absent'), ('FUTURE_DAY', 'Future Day'), ('BEFORE_JOINING', 'Before Joining')], default='WORKING_DAY', max_length=20),
        ),
    ]
