# Generated by Django 5.2.9 on 2026-01-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tracker_screenshot',
            field=models.CharField(blank=True, help_text='Cloudinary public ID / path for the screenshot', max_length=500, null=True),
        ),
    ]
