# Generated by Django 6.0 on 2025-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_manualattendancerequest_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualattendancerequest',
            name='hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
