# Generated by Django 5.2.9 on 2026-01-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_tracker_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='entry_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('TIMESHEET', 'Timesheet'), ('MANUAL', 'Manual')], default='REGULAR', max_length=20),
        ),
    ]
