# Generated by Django 6.0 on 2025-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_manualattendancerequest_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lunch_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='standup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
