# Generated by Django 5.2.9 on 2026-01-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_entry_type'),
        ('leaves', '0004_leavebalance_rh_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='leaves.leave'),
        ),
    ]
