# Generated by Django 6.0 on 2025-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_redundant_fields_and_add_hybrid_day'),
        ('attendance', '0010_attendance_lunch_end_time_and_more'),
    ]

    operations = [
    ]
