# Generated by Django 6.0 on 2025-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_redundant_fields_and_add_hybrid_day'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='attendance',
                    name='timesheet_admin_notes',
                ),
                migrations.RemoveField(
                    model_name='attendance',
                    name='timesheet_approved_at',
                ),
                migrations.RemoveField(
                    model_name='attendance',
                    name='timesheet_approved_by',
                ),
                migrations.RemoveField(
                    model_name='attendance',
                    name='timesheet_status',
                ),
                migrations.RemoveField(
                    model_name='attendance',
                    name='timesheet_submitted_at',
                ),
                migrations.RemoveField(
                    model_name='attendance',
                    name='tracker_screenshot',
                ),
            ]
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_day_before_joining',
            field=models.BooleanField(default=False, help_text='Is this day before employee joining date'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='seconds_actual_working_time',
            field=models.IntegerField(default=0, help_text='Actual working time in seconds'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(choices=[('WORKING_DAY', 'Working Day'), ('HALF_DAY', 'Half Day'), ('LEAVE_DAY', 'Leave Day'), ('HOLIDAY', 'Holiday'), ('WEEKEND_OFF', 'Weekend Off')], default='WORKING_DAY', help_text='Type of day', max_length=20),
        ),
    ]
